#!/usr/bin/env bash
# build.sh — Combines individual .sieve files into a single combined.sieve
# for upload to Proton Mail's sieve editor.
#
# Usage: ./build.sh
# Output: combined.sieve (in repo root)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILTERS_DIR="$SCRIPT_DIR/filters"
OUTPUT="$SCRIPT_DIR/combined.sieve"

# Header with require statement (needed once at the top)
cat > "$OUTPUT" << 'HEADER'
require ["environment", "variables", "relational", "comparator-i;ascii-numeric", "spamtest", "fileinto"];

# =============================================
# PROTON MAIL SIEVE FILTERS (auto-generated)
# Do not edit this file directly.
# Edit individual files in filters/ and run ./build.sh
# =============================================
HEADER

# Concatenate all .sieve files in numeric order
for f in "$FILTERS_DIR"/*.sieve; do
    filename="$(basename "$f")"
    echo "" >> "$OUTPUT"
    echo "# --- $filename ---" >> "$OUTPUT"
    cat "$f" >> "$OUTPUT"
done

echo ""
echo "✓ Built: $OUTPUT"
echo "  $(grep -c 'fileinto' "$OUTPUT") fileinto rules"
echo "  $(grep -c 'stop;' "$OUTPUT") stop directives"
echo ""
echo "Paste the contents into: Proton Mail → Settings → Filters → Sieve editor"
